<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>generateUploadFile</name>
   <tag></tag>
   <elementGuidId>6dcbceaf-b7de-43bd-8a50-e88beafcce31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'oxd-file-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68b4b186-4b0f-41b8-a936-102f6e2641f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-file-input</value>
      <webElementGuid>729778d3-3284-4bed-81d5-4ef8d66b9936</webElementGuid>
   </webElementProperties>
</WebElementEntity>
